"""초3 영어 진단 세트."""
from ._common import make_question, validate_elementary_questions
LEVEL,SUBJECT="초3","영어"
KEY=[2,1,3,4,1,2,3,1,2,4,1,3,2,1,3]
def q(n,a,s,t,o,c,sec,adv=False): return make_question(f"E3E-{n:02d}",LEVEL,SUBJECT,a,s,t,o,c,sec,f"{o[c-1]}가 알맞은 뜻 또는 응답입니다.",f"{s} 경험을 다시 확인할 필요가 있음.",adv)
QUESTIONS=[
q(1,"어휘·글자","기초 어휘","cat의 뜻은 무엇인가요?",["개","고양이","새","물고기","토끼"],2,25),q(2,"어휘·글자","첫 글자 인식","book과 같은 B로 시작하는 낱말을 고르세요.",["ball","apple","cat","dog","fish"],1,25),q(3,"어휘·글자","수 어휘","five는 몇인가요?",["3","4","5","6","7"],3,25),q(4,"어휘·글자","색깔 어휘","yellow의 뜻은 무엇인가요?",["빨간색","파란색","초록색","노란색","검은색"],4,25),q(5,"기본 의사소통","인사·자기소개","A: Hello, I'm Tom. B: ___",["Hi, Tom.","I'm nine.","It's blue.","Thank you.","No, I don't."],1,30),q(6,"기본 의사소통","이름 묻고 답하기","A: What's your name? B: ___",["I'm fine.","My name is Mina.","I'm ten.","It's a cat.","Goodbye."],2,30),q(7,"기본 의사소통","나이 묻고 답하기","A: How old are you? B: ___",["It's nine.","My name is Nine.","I'm nine.","Nine cats.","I like nine."],3,30),q(8,"기본 의사소통","사물 묻고 답하기","A: What's this? B: ___",["It is a pencil.","I'm a pencil.","Yes, I do.","I'm fine.","It's three."],1,30),q(9,"문장 이해","수량 표현","I have three balls. 공은 몇 개인가요?",["2","3","4","5","6"],2,30),q(10,"문장 이해","선호 표현","I like soccer.에서 좋아하는 것은 무엇인가요?",["milk","books","cats","soccer","apples"],4,30),q(11,"문장 이해","선호 질문 응답","A: Do you like apples? B: ___",["Yes, I do.","I'm ten.","It's an apple.","My name is Tom.","Good night."],1,30),q(12,"교실·상호작용","교실 지시 표현","Open your book.의 뜻은 무엇인가요?",["책을 덮으세요.","일어나세요.","책을 펴세요.","문을 닫으세요.","손을 내리세요."],3,25),q(13,"교실·상호작용","감사 응답","A: Thank you. B: ___",["I'm sorry.","You're welcome.","Good morning.","I'm nine.","It's blue."],2,25),q(14,"다음 학년 진입 탐색","능력 묻고 답하기","A: Can you swim? B: ___",["Yes, I can.","Yes, I do.","I'm swimming.","It's a swim.","I am nine."],1,35,True),q(15,"다음 학년 진입 탐색","시각 표현 이해","It's three o'clock.은 몇 시라는 뜻인가요?",["1시","2시","3시","4시","5시"],3,35,True)]
validate_elementary_questions(QUESTIONS,KEY,360,70)
QUESTION_SET={"level":LEVEL,"subject":SUBJECT,"curriculum":"2022 개정 교육과정 영어 3~4학년군 참고","curriculum_year":2026,"test_version":"E3_ENG_2022R_2026_v1.0","core_count":13,"advance_count":2,"display_name":"초3 영어 진단","questions":QUESTIONS}
