"""초2 기초영어 진단 세트."""
from ._common import make_question, validate_elementary_questions
LEVEL,SUBJECT="초2","영어"
KEY=[3,2,1,2,3,4,2,1,3,2,1,4,2,1,3]
def q(n,a,s,t,o,c,sec,adv=False): return make_question(f"E2E-{n:02d}",LEVEL,SUBJECT,a,s,t,o,c,sec,f"{o[c-1]}가 알맞은 뜻 또는 응답입니다.",f"{s} 경험을 다시 확인할 필요가 있음.",adv)
QUESTIONS=[
q(1,"알파벳·글자","알파벳 순서","M, N 다음에 오는 알파벳은 무엇인가요?",["M","N","O","P","Q"],3,20),q(2,"알파벳·글자","대소문자 대응","대문자 G와 짝이 되는 소문자는 무엇인가요?",["q","g","j","d","p"],2,20),q(3,"알파벳·글자","첫 글자 인식","F로 시작하는 영어 낱말을 고르세요.",["fish","book","cat","dog","apple"],1,25),q(4,"기초 어휘","동물 어휘","dog의 뜻은 무엇인가요?",["고양이","개","새","물고기","토끼"],2,25),q(5,"기초 어휘","색깔 어휘","blue의 뜻은 무엇인가요?",["빨간색","노란색","파란색","초록색","흰색"],3,25),q(6,"기초 어휘","수 어휘","seven은 몇인가요?",["4","5","6","7","8"],4,20),q(7,"기초 어휘","복수 표현 이해","two cats에는 고양이가 몇 마리인가요?",["1","2","3","4","5"],2,25),q(8,"기본 표현","아침 인사","A: Good morning. B: ___",["Good morning.","Good night.","Thank you.","Sorry.","Goodbye."],1,25),q(9,"기본 표현","이름 묻고 답하기","A: What's your name? B: ___",["I'm fine.","I'm eight.","My name is Jisu.","It's blue.","Yes, I do."],3,30),q(10,"기본 표현","나이 묻고 답하기","A: How old are you? B: ___",["My name is Tom.","I am eight.","I'm fine.","It's a dog.","Thank you."],2,30),q(11,"기본 표현","교실 표현","Stand up.의 뜻은 무엇인가요?",["일어나세요.","앉으세요.","책을 덮으세요.","조용히 하세요.","문을 닫으세요."],1,25),q(12,"짧은 문장 이해","좋아하는 것","I like pizza.에서 좋아하는 것은 무엇인가요?",["milk","soccer","books","pizza","cats"],4,30),q(13,"짧은 문장 이해","소유 표현 이해","This is my bag.에서 말하는 물건은 무엇인가요?",["book","bag","pencil","desk","chair"],2,30),q(14,"다음 학년 진입 탐색","선호 질문 응답","A: Do you like milk? B: ___",["Yes, I do.","I'm nine.","It's a book.","Good morning.","My name is Mina."],1,35,True),q(15,"다음 학년 진입 탐색","수량 표현 이해","There are three apples. How many apples are there?",["One.","Two.","Three.","Four.","Five."],3,35,True)]
validate_elementary_questions(QUESTIONS,KEY,330,70)
QUESTION_SET={"level":LEVEL,"subject":SUBJECT,"curriculum":"학원 기초영어 진단 · 초3 영어 진입 참고","curriculum_year":2026,"test_version":"E2_ENG_FOUNDATION_2026_v1.0","core_count":13,"advance_count":2,"display_name":"초2 기초영어 진단","questions":QUESTIONS}
